[build]
  ignore = "git log -1 --pretty=%B | grep dependabot"
  command = "yarn run build"
  publish = "dist"
  functions = ".netlify/functions"
  NODE_ENV = "8.9.0"

[[headers]]
  for = "/*"
  [headers.values]
  Link = '''
  </fonts/roboto-regular.woff2>; rel=preload; as=font
  </fonts/dosis-regular.woff2>; rel=preload; as=font'''
