---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/ateliers
  label: Ateliers
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - atelier
- type: directory
  path: src/agenda
  label: Événements
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - evenement
- type: directory
  path: src/interviews
  label: Interviews
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - interview
- type: directory
  path: src/blog
  label: Blog
  create: documents
  match: "*.md"
  templates:
  - billet
- type: directory
  path: src
  label: Pages
  create: all
  match: "*.md"
  templates:
  - page
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: gulp build
  publish_command: gulp build
  preview_env:
  - ELEVENTY_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: dist
  instant_preview_command: yarn start
  preview_docker_image: node:10
  mount_path: "/srv"
