backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "src/images/"
public_folder: "/images/"

collections:
  - name: 'evenements'
    label: 'Événements'
    folder: 'src/site/evenements'
    extension: 'md'
    preview_path: "evenements/{{year}}/{{month}}/{{day}}/{{slug}}/"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}.md'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', buttons: ['bold', 'italic', 'link', 'heading-one', 'heading-two', 'quote', 'bulleted-list', 'numbered-list'] }
