# https://ericjinks.com/blog/2019/netlify-scheduled-build/

name: Trigger Netlify Build
on:
  schedule:
    # Runs at 7am (5am UTC) every day
    - cron: "0 5 * * *"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5c952b432938fa018c9f37d5
